In [7]:
#install package
!pip3 install datamart-profiler
!pip3 install datamart_geo

^C

In [4]:
import pandas as pd
import pathlib
#import geopandas

In [46]:
import datamart_geo
import datamart_profiler

In [36]:
path = pathlib.Path().absolute()

In [37]:
df = {}
geodf = {}

In [51]:
import os
counter = 0
directory = os.path.join("c:\\",path)
for root,dirs,files in os.walk(directory):
    for file in files:
        if file.endswith(".csv"):
            f=pd.read_csv(file)
            df[counter] = f
            counter +=1

/Users/Xianbo/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (10,19,24) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/Users/Xianbo/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/Users/Xianbo/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (24) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [55]:
result0 = datamart_profiler.process_dataset(df[0])

In [56]:
result0

{'nb_rows': 53316,
 'nb_profiled_rows': 53316,
 'nb_columns': 36,
 'columns': [{'name': 'TR6_NO',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': [],
   'num_distinct_values': 53297},
  {'name': 'CONTROL_NO',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 0.0,
   'num_distinct_values': 42260,
   'mean': 719593.7232725635,
   'stddev': 86482.32142908248,
   'coverage': [{'range': {'gte': 600683.0, 'lte': 612483.0}},
    {'range': {'gte': 700687.0, 'lte': 713227.0}},
    {'range': {'gte': 800814.0, 'lte': 818342.0}}]},
  {'name': 'FILING_TYPE',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'num_distinct_values': 4},
  {'name': 'CYCLE',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 0.0,
   'num_distinct_values': 4,
   'mean': 7.122814914847325,
   'stddev': 0.8576117627797191,
   'coverage': [{'range': {'gte': 6.0, 'lte': 6.0}},
    {'range': {'gte': 7.0, 'lte': 7.0}},
    {'range': {'gte': 8.0, 'lte': 8.0}}]},
  {'name': 'BIN',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 0.0,
   'missing_values_ratio': 0.0005251706804711531,
   'num_distinct_values': 15169,
   'mean': 1942338.8667054495,
   'stddev': 1219511.5557411117,
   'coverage': [{'range': {'gte': 1003141.0, 'lte': 1086764.0}},
    {'range': {'gte': 2002824.0, 'lte': 2114119.0}},
    {'range': {'gte': 3029636.0, 'lte': 4535114.0}}]},
  {'name': 'HOUSE_NO',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'num_distinct_values': 4068},
  {'name': 'STREET_NAME',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'num_distinct_values': 2462},
  {'name': 'BOROUGH',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'num_distinct_values': 5},
  {'name': 'BLOCK',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 0.0,
   'num_distinct_values': 3606,
   'mean': 2368.702903443619,
   'stddev': 2731.832995369961,
   'coverage': [{'range': {'gte': 157.0, 'lte': 2514.0}},
    {'range': {'gte': 3142.0, 'lte': 7405.0}}]},
  {'name': 'LOT',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 0.0,
   'num_distinct_values': 443,
   'mean': 1068.4394928351714,
   'stddev': 2570.8348095384217,
   'coverage': [{'range': {'gte': 1.0, 'lte': 110.0}},
    {'range': {'gte': 7501.0, 'lte': 7506.0}}]},
  {'name': 'SEQUENCE_NO',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 5.6268287193337834e-05,
   'missing_values_ratio': 0.021569510090779502,
   'num_distinct_values': 113,
   'mean': 2.0352420205118373,
   'stddev': 3.4854343328531274,
   'coverage': [{'range': {'gte': 1.0, 'lte': 3.0}}]},
  {'name': 'SUBMITTED_ON',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration',
    'http://schema.org/DateTime'],
   'missing_values_ratio': 0.14125215695100907,
   'num_distinct_values': 3999,
   'mean': 1366838282.422278,
   'stddev': 138416831.6248218,
   'coverage': [{'range': {'gte': 1138752000.0, 'lte': 1259625600.0}},
    {'range': {'gte': 1293667200.0, 'lte': 1434412800.0}},
    {'range': {'gte': 1452816000.0, 'lte': 1594857600.0}}],
   'temporal_resolution': 'day'},
  {'name': 'CURRENT_STATUS',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'missing_values_ratio': 0.006939755420511666,
   'num_distinct_values': 4},
  {'name': 'QEWI_NAME',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'missing_values_ratio': 0.16767949583614675,
   'num_distinct_values': 2081},
  {'name': 'QEWI_BUS_NAME',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': [],
   'missing_values_ratio': 0.18182159201740566,
   'num_distinct_values': 4636},
  {'name': 'QEWI_BUS_STREET_NAME',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'missing_values_ratio': 0.1418523520144047,
   'num_distinct_values': 3826},
  {'name': 'QEWI_CITY',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'missing_values_ratio': 0.15113661940130543,
   'num_distinct_values': 528},
  {'name': 'QEWI_STATE',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'missing_values_ratio': 0.141908620301598,
   'num_distinct_values': 16},
  {'name': 'QEWI_ZIP',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 0.0011441218395978692,
   'missing_values_ratio': 0.7382399279765924,
   'num_distinct_values': 205,
   'mean': 232292.55789852465,
   'stddev': 7969815.126162617,
   'coverage': [{'range': {'gte': 7512.0, 'lte': 11572.0}}]},
  {'name': 'QEWI_NYS_LIC_NO',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'missing_values_ratio': 0.7377710255833145,
   'num_distinct_values': 430},
  {'name': 'OWNER_NAME',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': [],
   'missing_values_ratio': 0.7374896841473478,
   'num_distinct_values': 5015},
  {'name': 'OWNER_BUS_NAME',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': [],
   'missing_values_ratio': 0.13080501162877936,
   'num_distinct_values': 23841},
  {'name': 'OWNER_BUS_STREET_NAME',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': [],
   'missing_values_ratio': 0.12780403631180134,
   'num_distinct_values': 13523},
  {'name': 'OWNER_CITY',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'missing_values_ratio': 0.1302610848525771,
   'num_distinct_values': 705},
  {'name': 'OWNER_ZIP',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 0.0012379023182534324,
   'missing_values_ratio': 0.7380336109235501,
   'num_distinct_values': 469,
   'mean': 131865.63700453204,
   'stddev': 3554723.4078932544,
   'coverage': [{'range': {'gte': 10002.0, 'lte': 11418.0}}]},
  {'name': 'OWNER_STATE',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'missing_values_ratio': 0.7379773426363568,
   'num_distinct_values': 27},
  {'name': 'FILING_DATE',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration',
    'http://schema.org/DateTime'],
   'missing_values_ratio': 0.14132718133393352,
   'num_distinct_values': 4012,
   'mean': 1367517699.2628384,
   'stddev': 139236820.08833507,
   'coverage': [{'range': {'gte': 1138752000.0, 'lte': 1259539200.0}},
    {'range': {'gte': 1293926400.0, 'lte': 1434672000.0}},
    {'range': {'gte': 1453852800.0, 'lte': 1596067200.0}}],
   'temporal_resolution': 'day'},
  {'name': 'FILING_STATUS',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'num_distinct_values': 4},
  {'name': 'PRIOR_CYCLE_FILING_DATE',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/DateTime'],
   'missing_values_ratio': 0.28636806962262734,
   'num_distinct_values': 4534,
   'mean': 1191487290.9671993,
   'stddev': 167724579.4644828,
   'coverage': [{'range': {'gte': 937785600.0, 'lte': 1052438400.0}},
    {'range': {'gte': 1126224000.0, 'lte': 1248998400.0}},
    {'range': {'gte': 1305763200.0, 'lte': 1519084800.0}}],
   'temporal_resolution': 'day'},
  {'name': 'PRIOR_STATUS',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/Enumeration'],
   'missing_values_ratio': 0.23658939155225447,
   'num_distinct_values': 4},
  {'name': 'FIELD_INSPECTION_COMPLETED_DATE',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/DateTime'],
   'missing_values_ratio': 0.22190336859479332,
   'num_distinct_values': 4670,
   'mean': 1363627292.074533,
   'stddev': 148582987.04756668,
   'coverage': [{'range': {'gte': 1120608000.0, 'lte': 1245369600.0}},
    {'range': {'gte': 1288310400.0, 'lte': 1431907200.0}},
    {'range': {'gte': 1453939200.0, 'lte': 1594857600.0}}],
   'temporal_resolution': 'day'},
  {'name': 'QEWI_SIGNED_DATE',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': ['http://schema.org/DateTime'],
   'missing_values_ratio': 0.2370582939455323,
   'num_distinct_values': 4651,
   'mean': 1365486916.838115,
   'stddev': 143895224.34708977,
   'coverage': [{'range': {'gte': 1133827200.0, 'lte': 1242777600.0}},
    {'range': {'gte': 1274140800.0, 'lte': 1409097600.0}},
    {'range': {'gte': 1436918400.0, 'lte': 1593028864.0}}],
   'temporal_resolution': 'day'},
  {'name': 'LATE_FILING_AMT',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 0.0,
   'missing_values_ratio': 0.022826168504764047,
   'num_distinct_values': 527,
   'mean': 5914.316013743066,
   'stddev': 9923.629846712493,
   'coverage': [{'range': {'gte': 0.0, 'lte': 7250.0}},
    {'range': {'gte': 9000.0, 'lte': 27150.0}}]},
  {'name': 'FAILURE_TO_FILE_AMT',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 0.0,
   'missing_values_ratio': 0.022826168504764047,
   'num_distinct_values': 17,
   'mean': 1432.5802798518205,
   'stddev': 2926.2545128644456,
   'coverage': [{'range': {'gte': 0.0, 'lte': 2000.0}},
    {'range': {'gte': 4000.0, 'lte': 8000.0}}]},
  {'name': 'FAILURE_TO_COLLECT_AMT',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 0.0,
   'missing_values_ratio': 0.022826168504764047,
   'num_distinct_values': 55,
   'mean': 2270.312290063149,
   'stddev': 11962.276990137587,
   'coverage': [{'range': {'gte': 0.0, 'lte': 5000.0}}]},
  {'name': 'COMMENTS',
   'structural_type': 'http://schema.org/Text',
   'semantic_types': [],
   'missing_values_ratio': 0.7113436866981769,
   'num_distinct_values': 8558}],
 'nb_temporal_columns': 5,
 'nb_categorical_columns': 14,
 'nb_numerical_columns': 11,
 'types': ['categorical', 'numerical', 'temporal'],
 'attribute_keywords': ['TR6_NO',
  'TR',
  '6',
  'NO',
  'CONTROL_NO',
  'CONTROL',
  'NO',
  'FILING_TYPE',
  'FILING',
  'TYPE',
  'CYCLE',
  'BIN',
  'HOUSE_NO',
  'HOUSE',
  'NO',
  'STREET_NAME',
  'STREET',
  'NAME',
  'BOROUGH',
  'BLOCK',
  'LOT',
  'SEQUENCE_NO',
  'SEQUENCE',
  'NO',
  'SUBMITTED_ON',
  'SUBMITTED',
  'ON',
  'CURRENT_STATUS',
  'CURRENT',
  'STATUS',
  'QEWI_NAME',
  'QEWI',
  'NAME',
  'QEWI_BUS_NAME',
  'QEWI',
  'BUS',
  'NAME',
  'QEWI_BUS_STREET_NAME',
  'QEWI',
  'BUS',
  'STREET',
  'NAME',
  'QEWI_CITY',
  'QEWI',
  'CITY',
  'QEWI_STATE',
  'QEWI',
  'STATE',
  'QEWI_ZIP',
  'QEWI',
  'ZIP',
  'QEWI_NYS_LIC_NO',
  'QEWI',
  'NYS',
  'LIC',
  'NO',
  'OWNER_NAME',
  'OWNER',
  'NAME',
  'OWNER_BUS_NAME',
  'OWNER',
  'BUS',
  'NAME',
  'OWNER_BUS_STREET_NAME',
  'OWNER',
  'BUS',
  'STREET',
  'NAME',
  'OWNER_CITY',
  'OWNER',
  'CITY',
  'OWNER_ZIP',
  'OWNER',
  'ZIP',
  'OWNER_STATE',
  'OWNER',
  'STATE',
  'FILING_DATE',
  'FILING',
  'DATE',
  'FILING_STATUS',
  'FILING',
  'STATUS',
  'PRIOR_CYCLE_FILING_DATE',
  'PRIOR',
  'CYCLE',
  'FILING',
  'DATE',
  'PRIOR_STATUS',
  'PRIOR',
  'STATUS',
  'FIELD_INSPECTION_COMPLETED_DATE',
  'FIELD',
  'INSPECTION',
  'COMPLETED',
  'DATE',
  'QEWI_SIGNED_DATE',
  'QEWI',
  'SIGNED',
  'DATE',
  'LATE_FILING_AMT',
  'LATE',
  'FILING',
  'AMT',
  'FAILURE_TO_FILE_AMT',
  'FAILURE',
  'TO',
  'FILE',
  'AMT',
  'FAILURE_TO_COLLECT_AMT',
  'FAILURE',
  'TO',
  'COLLECT',
  'AMT',
  'COMMENTS']}

In [57]:
type(result0)

dict

In [61]:
pd.set_option('display.max_columns', 40)

In [62]:
df[0].head()

,TR6_NO,CONTROL_NO,FILING_TYPE,CYCLE,BIN,HOUSE_NO,STREET_NAME,BOROUGH,BLOCK,LOT,SEQUENCE_NO,SUBMITTED_ON,CURRENT_STATUS,QEWI_NAME,QEWI_BUS_NAME,QEWI_BUS_STREET_NAME,QEWI_CITY,QEWI_STATE,QEWI_ZIP,QEWI_NYS_LIC_NO,OWNER_NAME,OWNER_BUS_NAME,OWNER_BUS_STREET_NAME,OWNER_CITY,OWNER_ZIP,OWNER_STATE,FILING_DATE,FILING_STATUS,PRIOR_CYCLE_FILING_DATE,PRIOR_STATUS,FIELD_INSPECTION_COMPLETED_DATE,QEWI_SIGNED_DATE,LATE_FILING_AMT,FAILURE_TO_FILE_AMT,FAILURE_TO_COLLECT_AMT,COMMENTS
0,TR6-809827-8B-I1,809827,Initial,8,3324275.0,908,ASHFORD STREET,BROOKLYN,4377,1,2,2017-04-12 00:00:00,SAFE,TIMOTHY WEBB,NaN,505 8TH AVENUE,NEW YORK,NY,10018,RA - 031877,GARY GUILLAUME,NYC HOUSING AUTHORITY,90 CHURCH ST,NEW YORK,10004,NY,04/12/2017 12:00:00 AM,SAFE,12/23/2015 12:00:00 AM,SAFE,02/16/2017 12:00:00 AM,03/30/2017 12:00:00 AM,0.0,0.0,0.0,NaN
1,TR6-802289-8A-I1,802289,Initial,8,1016111.0,103,FIFTH AVENUE,MANHATTAN,846,4,1,2016-09-23 00:00:00,SAFE,THOMAS CATALDO,NaN,440 WAVERLY AVENUE,PATCHOGUE,NY,11772,PE - 084457,DAVID MAGIER,Harlington Realty Co.,156A EAST 83RD STREE,NEW YORK,10028,NY,09/23/2016 12:00:00 AM,SAFE,02/21/2012 12:00:00 AM,SAFE,09/09/2016 12:00:00 AM,09/23/2016 04:00:00 AM,0.0,0.0,0.0,NaN
2,TR6-813209-8A-I1,813209,Initial,8,1056563.0,2700,BROADWAY,MANHATTAN,1875,7501,1,2016-12-19 00:00:00,SWARMP,SCOTT HENSON,NaN,27 WEST 20TH STREET,NEW YORK,NY,10011,RA - 028626,EDWARD MCARTHUR,COLUMBIA UNIVERSITY,410 W 118TH ST,NEW YORK,10027,NY,12/19/2016 12:00:00 AM,SWARMP,02/08/2011 12:00:00 AM,SAFE,11/30/2016 12:00:00 AM,12/07/2016 12:00:00 AM,0.0,0.0,0.0,NaN
3,TR6-807808-8A-I1,807808,Initial,8,2008009.0,1515,GRAND CONCOURSE,BRONX,2835,16,1,2016-11-01 00:00:00,SAFE,THOMAS CATALDO,NaN,440 WAVERLY AVENUE,PATCHOGUE,NY,11772,PE - 084457,BROOKE MORGAN,The Morgan Group,41 WEST PUTNAM AVE,GREENWICH,06830,CT,11/01/2016 12:00:00 AM,SAFE,08/18/2014 12:00:00 AM,SAFE,10/05/2016 12:00:00 AM,11/01/2016 12:00:00 AM,7500.0,2000.0,0.0,NaN
4,TR6-800320-8A-I1,800320,Initial,8,1001473.0,261,BROADWAY,MANHATTAN,135,7501,1,2017-02-06 00:00:00,SAFE,ERIC COWLEY,NaN,1100 SUMMER STREET,STAMFORD,CT,06905,PE - 070906,SOPHIE CARRINGTON,FIRSTSERVICE RESIDENTIAL,622 THIRD AVE 15TH F,NEW YORK,10017,NY,02/02/2018 12:00:00 AM,UNSAFE,10/14/2011 12:00:00 AM,SAFE,02/21/2018 12:00:00 AM,03/18/2018 08:00:00 PM,3000.0,0.0,1000.0,INITIAL REPORT FILED 7/18/16 WAS REJECTED

In [65]:
df[2].head()

,Application ID,License Number,License Type,Application or Renewal,Business Name,Status,Start Date,End Date,Temp Op Letter Issued,Temp Op Letter Expiration,License Category,Application Category,Building Number,Street,Street 2,Unit Type,Unit,Description,City,State,Zip,Contact Phone,Longitude,Latitude,Active Vehicles
0,1066-2017-RHIC,1294131-DCA,Business,Renewal,PEYKO TZENOV,Issued,01/09/2017,01/10/2017,NaN,NaN,Home Improvement Contractor,Special,3280,RESERVOIR OVAL E,NaN,NaN,NaN,NaN,BRONX,NY,10467,9178047161,-73.877091,40.876214,NaN
1,1164-2019-RDPD,1472251-DCA,Business,Renewal,AMERICAN EAST PHARMACY INC.,Issued,01/09/2019,01/10/2019,NaN,NaN,Dealer In Products,Basic,23,DIVISION ST,NaN,NaN,NaN,NaN,NEW YORK,NY,10002,2129251900,-73.996169,40.714118,NaN
2,33701-2016-RELE,2025971-DCA,Business,Renewal,LUCAS ELECTRONICS INC,Issued,12/31/2016,01/10/2017,NaN,NaN,Electronics Store,Basic,886,MANHATTAN AVE,NaN,NaN,NaN,NaN,BROOKLYN,NY,11222,347-987-3235,-73.954098,40.729869,NaN
3,34278-2018-RELE,2047043-DCA,Business,Renewal,ELITE WIRELESS GROUP NY LLC,Issued,12/31/2018,01/08/2019,NaN,NaN,Electronics Store,Basic,3015,CHURCH AVE,NaN,NaN,NaN,NaN,BROOKLYN,NY,11226,718-484-7746,-73.949327,40.650826,NaN
4,3891-2019-ALAU,2085269-DCA,Business,Application,"A-LIN LAUNDROMAT, INC.",Issued,04/07/2019,05/02/2019,NaN,NaN,Laundries,Basic,5509,4TH AVE,NaN,NaN,NaN,NaN,BROOKLYN,NY,11220,NaN,-74.015602,40.643549,NaN

In [107]:
#result2 = datamart_profiler.process_dataset(df[2])
#check_lat(result2['columns'])

In [136]:
check_lat(result2['columns'])

True

In [129]:
df[2]['State'].unique()

array(['NY', 'NV', 'KY', 'NJ', 'MA', nan, 'TX', 'FL', 'GA', 'NC', 'AZ',
       'MI', 'CA', 'CT', 'MO', 'MD', 'VA', 'MN', 'ME',
       'Metro Manila, Philippines', 'IL', 'OR', 'AR', 'DC', 'WA', 'MS',
       'OH', 'DE', 'SC', 'CYBERPARK ALABANG', 'IA', 'CHIH.', 'ALABANG',
       'TONK ROAD, JAIPUR', 'IN', 'CO', 'LA', 'SW', 'UT', 'INDIA', 'PA',
       'PH', 'BATAAN', 'JAMAICA', 'ONTARIO', 'MAHARASHTRA',
       'MAHARTASHTRA', 'AL', 'TN', 'JA', 'MUNTINLUPA CITY', 'MANILA',
       'KS', 'SD', 'HEREDIA', 'WI', 'HARYANA', 'RI', 'NH', 'ND', 'MX',
       'PHILIPINES', 'KARNATAKA', 'ID', 'india', 'NE', 'ON',
       'ILOILO CITY', 'RJ', 'OK', 'GC', 'PHILIPPINES', 'WY', 'PUNE',
       'JALISCO', 'QUEZON CITY', 'TONK ROAD JAIPUR', 'Haryana',
       'TAGUIG CITY', 'PAMPANGA', 'CYBERPARK ALABAND', 'PR', 'ENGLAND',
       'TAGUIC CITY', 'QC', 'MEXICO C.P.', 'METRO MANILLA',
       'METRO MANILA PH', 'METRO MANILA', 'HI', 'BC', 'ANGELES CITY',
       'UTTAR PRADESH', 'VT', 'JM', 'India', 'BANGALORE', 'ANDHRA PRADES',
       'MUMBAI', 'St Croix', 'WV', 'INDIAN', 'MT', 'AK', 'INDIA121003',
       'NM', 'VI', 'PANAMA', 'BENGUET', 'SONORA', 'ontario', 'Antioquia',
       'RHONE', 'METRO MANILA, PHILIPPINES 1111', 'ST CATHERINE, JAMAICA',
       'DE MEXICO', 'CN', 'ST. ANDREW', 'COSTA RICA', 'Ontario', 'QUEBEC',
       'FRANCE', 'IT', 'New York', 'SONORA, MEXICO', 'ST JAMES',
       'WEST INDIES', 'ONTARIO M3B 1Z6', 'DN', 'DR 10122',
       'HARYANA. INDIA', 'Jamaica', 'Maharashtra',
       'QUEZON CITY PHILLPPINES', 'Panama', 'COLUMBIA', 'MAHARASHTA',
       'PN', 'QB', 'N', 'Aichi-ken', 'LONDON', 'nj', 'MB', 'NW', 'BERLIN',
       'ny', 'Seoul', 'Delhi', 'ON   L0E 1E0', 'ON  M2N6N5', 'France',
       'toulouse', 'Cheshire', 'Muntinlupa City', 'GR', 'MB R3B',
       'Taguig City', 'JAMAICA WI', 'ATLANTICO', 'PUNI', 'LAGUNA',
       'GUJARAT', 'MAHARASH', 'MONT BLANC', 'QUEBEC CA'], dtype=object)

In [110]:
df[2]

,Application ID,License Number,License Type,Application or Renewal,Business Name,Status,Start Date,End Date,Temp Op Letter Issued,Temp Op Letter Expiration,License Category,Application Category,Building Number,Street,Street 2,Unit Type,Unit,Description,City,State,Zip,Contact Phone,Longitude,Latitude,Active Vehicles
0,1066-2017-RHIC,1294131-DCA,Business,Renewal,PEYKO TZENOV,Issued,01/09/2017,01/10/2017,NaN,NaN,Home Improvement Contractor,Special,3280,RESERVOIR OVAL E,NaN,NaN,NaN,NaN,BRONX,NY,10467,9178047161,-73.877091,40.876214,NaN
1,1164-2019-RDPD,1472251-DCA,Business,Renewal,AMERICAN EAST PHARMACY INC.,Issued,01/09/2019,01/10/2019,NaN,NaN,Dealer In Products,Basic,23,DIVISION ST,NaN,NaN,NaN,NaN,NEW YORK,NY,10002,2129251900,-73.996169,40.714118,NaN
2,33701-2016-RELE,2025971-DCA,Business,Renewal,LUCAS ELECTRONICS INC,Issued,12/31/2016,01/10/2017,NaN,NaN,Electronics Store,Basic,886,MANHATTAN AVE,NaN,NaN,NaN,NaN,BROOKLYN,NY,11222,347-987-3235,-73.954098,40.729869,NaN
3,34278-2018-RELE,2047043-DCA,Business,Renewal,ELITE WIRELESS GROUP NY LLC,Issued,12/31/2018,01/08/2019,NaN,NaN,Electronics Store,Basic,3015,CHURCH AVE,NaN,NaN,NaN,NaN,BROOKLYN,NY,11226,718-484-7746,-73.949327,40.650826,NaN
4,3891-2019-ALAU,2085269-DCA,Business,Application,"A-LIN LAUNDROMAT, INC.",Issued,04/07/2019,05/02/2019,NaN,NaN,Laundries,Basic,5509,4TH AVE,NaN,NaN,NaN,NaN,BROOKLYN,NY,11220,NaN,-74.015602,40.643549,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377035,12846-2019-RGAR,2074988-DCA,Business,Renewal,"LAZ PARKING NEW YORK/NEW JERSEY, LLC",Issued,02/28/2019,03/01/2019,NaN,NaN,Garage,Basic,420,E 20TH ST,NaN,NaN,NaN,NaN,NEW YORK,NY,10009,2122652239,-73.978703,40.734392,NaN
377036,4279-2019-AGPL,2084834-DCA,Business,Application,"LAZ PARKING NEW YORK/NEW JERSEY, LLC",Pending,04/15/2019,04/18/2019,2019-04-18,6/27/2019,Garage and Parking Lot,Basic,160,RIVERSIDE BLVD,NaN,NaN,NaN,NaN,NEW YORK,NY,10069,2122652239,-73.988716,40.777807,NaN
377037,5898-2020-REHD,2043084-DCA,Business,Renewal,AUTO SOUND SECURITY & TINT CORP,Issued,06/04/2020,06/05/2020,NaN,NaN,Electronic & Appliance Service,Basic,24722F,S CONDUIT AVE,NaN,NaN,NaN,NaN,ROSEDALE,NY,11422,7183950554,-73.730654,40.665349,NaN
377038,5778-2020-RSSG,1239998-DCA,Individual,Renewal,STACEY M NEWSOME,Issued,03/31/2020,06/11/2020,NaN,NaN,Sightseeing Guide,Basic,NaN,NaN,NaN,NaN,NaN,NaN,SHERMAN OAKS,CA,91423,NaN,NaN,NaN,NaN
377039,5777-2020-RSSG,2034708-DCA,Individual,Renewal,PIM ZEEGERS,Issued,03/25/2020,06/11/2020,NaN,NaN,Sightseeing Guide,Basic,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NY,11211,NaN,NaN,NaN,NaN

In [114]:
df[2].columns

Index(['Application ID', 'License Number', 'License Type',
       'Application or Renewal', 'Business Name', 'Status', 'Start Date',
       'End Date', 'Temp Op Letter Issued', 'Temp Op Letter Expiration',
       'License Category', 'Application Category', 'Building Number', 'Street',
       'Street 2', 'Unit Type', 'Unit', 'Description', 'City', 'State', 'Zip',
       'Contact Phone', 'Longitude', 'Latitude', 'Active Vehicles'],
      dtype='object')

In [127]:
len(df[2]["State"].unique())

166

In [115]:
for i in result2['columns']:
    print(i["name"])

Application ID
License Number
License Type
Application or Renewal
Business Name
Status
Start Date
End Date
Temp Op Letter Issued
Temp Op Letter Expiration
License Category
Application Category
Building Number
Street
Street 2
Unit Type
Unit
Description
City
State
Zip
Contact Phone
Longitude
Latitude
Active Vehicles

In [84]:
def check_lat(col_list):
    for content in col_list:
        if 'semantic_types' in content:
            if content['semantic_types'] ==['http://schema.org/latitude']:
                return True
    return False

In [87]:
check_lat(result2['columns'])

True

In [79]:
result2['columns'][-2]

{'name': 'Latitude',
 'structural_type': 'http://schema.org/Float',
 'semantic_types': ['http://schema.org/latitude'],
 'unclean_values_ratio': 0.0,
 'missing_values_ratio': 0.4332139826013155,
 'mean': 40.723340840195014,
 'stddev': 0.0812830146882331,
 'coverage': [{'range': {'gte': 40.560615500000004,
    'lte': 40.674083200000005}},
  {'range': {'gte': 40.6821307, 'lte': 40.773875399999994}},
  {'range': {'gte': 40.79016420000001, 'lte': 40.8848078}}]}

In [ ]:
>>> geo_data = datamart_geo.GeoData.download()  # Download data if needed

>>> france = geo_data.resolve_name('France')
>>> france
<datamart_geo.Area "Republic of France" (3017382) type=Type.ADMIN_0>
>>> france.latitude, france.longitude
(46.0, 2.0)
>>> france.bounds
(-61.797841, 55.854503, -21.370782, 51.087541)
>>> assert france.type == datamart_geo.Type.ADMIN_0
>>> assert france.type == datamart_geo.Type.COUNTRY

>>> cuers = geo_data.resolve_name('Cuers')
>>> cuers
<datamart_geo.Area "Cuers" (6451482) type=Type.ADMIN_4>
>>> cuers.latitude, cuers.longitude
(43.2375, 6.07083)
>>> cuers.get_parent_area()
<datamart_geo.Area "Arrondissement de Toulon" (2972326) type=Type.ADMIN_3>

>>> [
...     # Show multiple results with their parent ADMIN_1
...     (a, a.get_parent_area(datamart_geo.Type.ADMIN_1))
...     for a in geo_data.resolve_name_all('Var')
... ]
[(<datamart_geo.Area "Var" (2970749) type=Type.ADMIN_2>,
  <datamart_geo.Area "Provence-Alpes-Côte d'Azur" (2985244) type=Type.ADMIN_1>),
 (<datamart_geo.Area "Vars" (6427887) type=Type.ADMIN_4>,
  <datamart_geo.Area "Nouvelle-Aquitaine" (11071620) type=Type.ADMIN_1>),
 (<datamart_geo.Area "Vars" (6442138) type=Type.ADMIN_4>,
  <datamart_geo.Area "Bourgogne-Franche-Comté" (11071619) type=Type.ADMIN_1>)]